import os

# Required channel configuration
REQUIRED_CHANNEL = os.getenv("REQUIRED_CHANNEL", "@FreelanceTM_channel")

TEXTS = {
    "ru": {
        "welcome": "🎉 Добро пожаловать в FreelanceTM!\n\n💼 Платформа для фрилансеров и заказчиков\n🔒 Гарантия безопасных сделок\n⭐ Система отзывов и рейтингов\n📢 Новости и обновления платформы\n🤝 Поддержка и помощь пользователям\n\nДля продолжения работы необходимо подписаться на наш канал:",
        "choose_language": "🌐 Выберите язык / Dil saýlaň:",
        "choose_role": "👤 Выберите вашу роль:",
        "registration_name": "👤 Введите ваше имя:",
        "registration_skills": "💼 Укажите ваши навыки:",
        "registration_description": "📝 Расскажите о себе:",
        "registration_contact": "📞 Укажите контакт для связи:",
        "registration_complete": "✅ Регистрация завершена! Добро пожаловать в FreelanceTM!",
        "main_menu_freelancer": "🏠 Главное меню фрилансера",
        "main_menu_client": "🏠 Главное меню заказчика",
        "btn_create_order": "➕ Создать заказ",
        "btn_view_orders": "📋 Просмотр заказов",
        "btn_my_orders": "📋 Мои заказы",
        "btn_my_responses": "📤 Мои отклики",
        "btn_profile": "👤 Профиль",
        "btn_reviews": "📝 Отзывы",
        "btn_help": "❓ Помощь",
        "btn_back": "◀️ Назад",
        "check_subscription": "✅ Проверить подписку",
        "subscription_required": "❌ Для использования бота необходимо подписаться на канал:",
        "order_title": "📝 Введите название заказа:",
        "order_description": "📋 Введите описание заказа:",
        "order_budget": "💰 Введите бюджет (в TMT):",
        "order_deadline": "⏰ Введите срок выполнения (в днях):",
        "order_contact": "📞 Введите контакт для связи:",
        "order_created": "✅ Заказ успешно создан!",
        "no_orders": "📭 Нет доступных заказов",
        "orders_list": "📋 Доступные заказы:",
        "my_orders_list": "📋 Ваши заказы:",
        "no_my_orders": "📭 У вас нет заказов",
        "respond_to_order": "📤 Откликнуться",
        "response_sent": "✅ Отклик отправлен!",
        "response_exists": "❌ Вы уже откликнулись на этот заказ",
        "error_not_freelancer": "❌ Эта функция доступна только фрилансерам",
        "error_not_client": "❌ Эта функция доступна только заказчикам",
        "error_order_not_found": "❌ Заказ не найден",
        "error_not_your_order": "❌ Это не ваш заказ",
        "profile_info": "👤 Ваш профиль:",
        "edit_profile": "✏️ Редактировать профиль",
        "edit_name": "✏️ Изменить имя",
        "edit_skills": "✏️ Изменить навыки",
        "edit_description": "✏️ Изменить описание",
        "edit_contact": "✏️ Изменить контакт",
        "profile_updated": "✅ Профиль обновлен",
        "leave_review": "⭐ Оставить отзыв",
        "select_rating": "⭐ Выберите оценку:",
        "enter_review_text": "📝 Напишите отзыв:",
        "review_added": "✅ Отзыв добавлен",
        "review_error": "❌ Не удалось добавить отзыв",
        "no_reviews": "📭 Отзывов пока нет",
        "reviews_about_you": "📝 Отзывы о вас:",
        "new_response": "📨 Новый отклик на ваш заказ!"
    },
    "tm": {
        "welcome": "🎉 FreelanceTM-a hoş geldiňiz!\n\n💼 Frilanserler we müşderiler üçin platforma\n🔒 Howpsuz geleşikleriň kepilligi\n⭐ Syn we reýting ulgamy\n📢 Platformanyň täzelikleri we täzelenmeler\n🤝 Ulanyjylara goldaw we kömek\n\nIşlemegi dowam etdirmek üçin kanalymyza ýazylyň:",
        "choose_language": "🌐 Выберите язык / Dil saýlaň:",
        "choose_role": "👤 Rolüňizi saýlaň:",
        "registration_name": "👤 Adyňyzy giriziň:",
        "registration_skills": "💼 Başarnyklaryňyzy görkeziň:",
        "registration_description": "📝 Öziňiz hakda aýdyň:",
        "registration_contact": "📞 Aragatnaşyk üçin kontakt görkeziň:",
        "registration_complete": "✅ Hasaba alyş tamamlandy! FreelanceTM-a hoş geldiňiz!",
        "main_menu_freelancer": "🏠 Frilanseriniň esasy menýusy",
        "main_menu_client": "🏠 Müşderiniň esasy menýusy",
        "btn_create_order": "➕ Sargyt döretmek",
        "btn_view_orders": "📋 Sargytlary görmek",
        "btn_my_orders": "📋 Meniň sargytlarym",
        "btn_my_responses": "📤 Meniň jogaplarym",
        "btn_profile": "👤 Profil",
        "btn_reviews": "📝 Synlar",
        "btn_help": "❓ Kömek",
        "btn_back": "◀️ Yza",
        "check_subscription": "✅ Ýazylmagy barlamak",
        "subscription_required": "❌ Botu ulanmak üçin kanala ýazylmaly:",
        "order_title": "📝 Sargydyň adyny giriziň:",
        "order_description": "📋 Sargydyň beýanyny giriziň:",
        "order_budget": "💰 Býudjeti giriziň (TMT-de):",
        "order_deadline": "⏰ Ýerine ýetirmek möhletini giriziň (günlerde):",
        "order_contact": "📞 Aragatnaşyk üçin kontakt giriziň:",
        "order_created": "✅ Sargyt üstünlikli döredildi!",
        "no_orders": "📭 Elýeterli sargyt ýok",
        "orders_list": "📋 Elýeterli sargytlar:",
        "my_orders_list": "📋 Siziň sargytlaryňyz:",
        "no_my_orders": "📭 Siziň sargydyňyz ýok",
        "respond_to_order": "📤 Jogap bermek",
        "response_sent": "✅ Jogap iberildi!",
        "response_exists": "❌ Siz bu sargyta eýýäm jogap berdiňiz",
        "error_not_freelancer": "❌ Bu funksiýa diňe frilanserler üçin elýeterli",
        "error_not_client": "❌ Bu funksiýa diňe müşderiler üçin elýeterli",
        "error_order_not_found": "❌ Sargyt tapylmady",
        "error_not_your_order": "❌ Bu siziň sargydyňyz däl",
        "profile_info": "👤 Siziň profilyňyz:",
        "edit_profile": "✏️ Profili üýtgetmek",
        "edit_name": "✏️ Ady üýtgetmek",
        "edit_skills": "✏️ Başarnyklary üýtgetmek",
        "edit_description": "✏️ Beýany üýtgetmek",
        "edit_contact": "✏️ Kontakty üýtgetmek",
        "profile_updated": "✅ Profil täzelendi",
        "leave_review": "⭐ Syn galdyrmak",
        "select_rating": "⭐ Bahany saýlaň:",
        "enter_review_text": "📝 Syn ýazyň:",
        "review_added": "✅ Syn goşuldy",
        "review_error": "❌ Syn goşup bolmady",
        "no_reviews": "📭 Heniz syn ýok",
        "reviews_about_you": "📝 Siziň barada synlar:",
        "new_response": "📨 Täze jogap!"
    }
}

CATEGORIES = {
    "ru": {
        "web_development": "💻 Веб-разработка",
        "mobile_development": "📱 Мобильная разработка",
        "design": "🎨 Дизайн",
        "writing": "✍️ Копирайтинг",
        "translation": "🌐 Переводы",
        "marketing": "📈 Маркетинг",
        "other": "🔧 Другое"
    },
    "tm": {
        "web_development": "💻 Web ösüş",
        "mobile_development": "📱 Mobil ösüş",
        "design": "🎨 Dizaýn",
        "writing": "✍️ Ýazuw",
        "translation": "🌐 Terjime",
        "marketing": "📈 Marketing",
        "other": "🔧 Beýleki"
    }
}
